// Generated by LiveScript 1.2.0
(function(){
  if (editing) {
    $('.kaki-block').resizable({
      stop: function(e, ui){
        return $.get(M.cfg.wwwroot + "/mod/kakiemon/ajax.php", {
          action: 'blockresize',
          id: cmid,
          block: $(e.target).data('id'),
          width: ui.size.width,
          height: ui.size.height
        });
      }
    });
  }
}).call(this);
